openapi: 3.0.0
info:
  title: API de Empresas
  version: 1.0.0
  description: API para gerenciar empresas
tags:
  - name: User
    description: Operações relacionadas a usuarios

paths:
  /user:
    $ref: './swagger/paths/user.yaml#/user'
  /user/{idUser}:
    $ref: './swagger/paths/user.yaml#/user-id'